# Generated by Django 5.1.1 on 2024-10-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('work_experiences', models.TextField()),
                ('educations', models.TextField()),
                ('selected_template', models.CharField(max_length=10)),
                ('selected_color', models.CharField(max_length=20)),
            ],
        ),
    ]
