# Generated by Django 5.1.1 on 2024-10-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='selected_color',
            field=models.CharField(max_length=50),
        ),
    ]
